export enum ToolName {
  SESSION_START = "session_start",
  SEARCH = "search",
  GET = "get",
  WRITE = "write",
  UPDATE = "update",
  INVALIDATE = "invalidate",
  RESTORE = "restore",
  CHECKPOINT = "checkpoint",
  LINK = "link",
  CODE_INDEX = "code_index",
  CODE_LOOKUP = "code_lookup",
  SOURCE_REGISTER = "source_register",
  MIRROR_UPSERT = "mirror_upsert",
  MIRROR_STATUS = "mirror_status",
  CONSOLIDATE_SUGGEST = "consolidate_suggest",
  CONSOLIDATE_APPLY = "consolidate_apply",
  STATS = "stats",
}
